version: "3.7"

services:
  fishare-identitycontext-container:
    image: mongo:latest
    restart: always
    container_name: fishare-identitycontext
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=identity
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin12345
    volumes:
      - MongoDB-Auth:/data/db
      - MongoDB-Auth:/data/configdb
    ports:
      - 27017:27017

  fishare-identityservice-container:
    image: fishare-identityservice-i
    container_name: fishare-identityservice
    build:
      context: ./src/services/Fishare.IdentityService
      dockerfile: Dockerfile
    volumes:
      - .:/fishare-identityservice
    environment:
      FLASK_ENV: development
    ports:
      - "3000:6000"
  
  fishare-usercontext-container:
    image: mysql:5.7.18
    container_name: fishare-usercontext
    environment:
      MYSQL_ROOT_PASSWORD: "p4ssw0r#"
      MYSQL_DATABASE: "Userservicedb"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  fishare-userservice-container:
    image: fishare-userservice-i
    container_name: fishare-userservice
    build:
      context: ./src/services/Fishare.UserService
      dockerfile: Dockerfile
    volumes:
      - .:/fishare-userservice
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
        # FISHARE_USERSERVICE_DB: "Server=fishare-usercontext;Database=FishareUserService;Uid=sa;Password=toor12345"
    ports:
      - "5000:5000"

volumes: 
  MongoDB-Auth:
    external: false
    name: "Identityservice-database"
  MYSQLDB-User:
    name: "Userservice-MYSQL"
