version: "3.3"

services:
  Auth-db:
    image: mongo
    container_name: fishare-auth-db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=authentication
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./Fishare-databases/init-auth-mongodb.js:/docker-entrypoint-initdb.d/init-auth-mongodb.js:ro
      - ./docker-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    ports:
      - "27017-27019:27017-27019"

  Auth-node:
    image: dcornelissen/fishare-auth-nest:latest
    container_name: fishare-auth-nest
    build:
      context: ./Fishare-microservices/auth-service
      dockerfile: dockerfile
    ports:
      - "3000:3000"
