version: "3.7"

services:
  Auth-db:
    image: mongo
    container_name: fishare-auth-db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=authentication
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - MongoDB-Auth:/data/db
      - MongoDB-Auth:/data/configdb
    ports:
      - 27017:27017

  Auth-node:
    image: fishare-auth-nest-i
    container_name: fishare-auth-nest
    build:
      context: ./Fishare-microservices/auth-service
      dockerfile: Dockerfile
    volumes:
      - .:/auth-service
    environment:
      FLASK_ENV: development
    ports:
      - "3000:3000"

volumes: 
  MongoDB-Auth:
    external: false
    name: "authservice-database"