apiVersion: v1
kind: Service
metadata:
  name: fishare-identity-service
spec:
  type: NodePort
  selector:
    app: fishare-identityservice
  ports:
    - name: broker
      protocol: TCP
      port: 6000
      targetPort: 6000