apiVersion : apps/v1
kind: Deployment
metadata:
  name: fishare-rabbitmq-deployment
  labels:
    broker: fishare-rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fishare-rabbitmq
  template:
    metadata:
      labels:
        app: fishare-rabbitmq
    spec:
      volumes:
      - name: rabbitmq-pvc-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
      containers:
        - name: fishare-rabbitmq
          image: rabbitmq:3.8.3-management
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-pvc-storage
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: FishyCookie
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
            - name: RABBITMQ_DEFAULT_VHOST
              value: fishare_Vhost
