apiVersion: v1
kind: Service
metadata:
  name: fishare-rabbitmq-service
spec:
  type: NodePort
  selector:
    app: fishare-rabbitmq
  ports:
    - name: broker
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: dashboard
      protocol: TCP
      port: 15672
      targetPort: 15672