trigger:
    paths:
      include:
        - src/Fishare-Angular*
    branches:
      include:
        - master
  
resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dcornelissen DockerHub'
  imageRepository: 'dcornelissen/Fishare-Angular'
  tag: '$(Build.BuildId)'
  solutionPath: 'src/Fishare-Angular'
  projectPath: '$(solutionPath)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:

- stage: Code_Quality
  displayName: Static Code Quality
  jobs:
  - job: CodeQuality
    displayName: SonarCloud Static Code Quality
    pool:
      vmImage: $(vmImageName)
    steps:            
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'fishare-angular'
          scannerMode: 'CLI'
          configMode: 'file'
          configFile: '$(solutionPath)/sonar-project.properties'
      - task: SonarCloudAnalyze@1
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'

- stage: Build
  displayName: Build and Analyze
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:        
      - task: Docker@2
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '$(solutionPath)/Dockerfile'
          tags: |
            $(tag)
            latest