trigger:
    paths:
      include:
        - src/Fishare-Angular*
    # branches:
    #   include:
    #     - master
  
resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dcornelissen DockerHub'
  imageRepository: 'dcornelissen/Fishare-Angular'
  tag: '$(Build.BuildId)'
  solutionPath: 'src/Fishare-Angular'
  projectPath: '$(solutionPath)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Analyze
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:        
      - task: Docker@2
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '$(solutionPath)/Dockerfile'
          tags: |
            $(tag)
            latest