apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: fishare-userservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fishare-userservice
  template:
    metadata:
      labels:
        app: fishare-userservice
    spec:
      containers:
      - name: fishare-userservice-container
        image: dcornelissen/fishare.userservice
        ports:
        - containerPort: 5000
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Docker
          - name: FISHARE_USERSERVICE_DB
            value: "Server=fishare-usercontext;Database=FUSDB;User Id=SA;Password=Toor12345;"
          - name: FISHARE_RBMQ_HOSTNAME
            value: fishare-rabbitmq
          - name: FISHARE_RBMQ_USERNAME
            value: user
          - name: FISHARE_RBMQ_PASSWORD
            value: password
          - name: FISHARE_RBMQ_VHOST
            value: fishare_Vhost
          - name: FISHARE_RBMQ_QUEUE
            value: user.queue
          - name: FISHARE_RBMQ_EXCHANGE
            value: fishare.user.topic
          - name: FISHARE_RBMQ_PORT
            value: 5672
