apiVersion: v1
kind: Service
metadata:
  name: fishare-user-service
spec:
  type: NodePort
  selector:
    app: fishare-userservice
  ports:
      protocol: TCP
      port: 5000
      targetPort: 5000